package amyc
package codegen

import analyzer._
import amyc.ast.Identifier
import amyc.ast.SymbolicTreeModule.{Call => AmyCall, Div => AmyDiv, And => AmyAnd, Or => AmyOr, _}
import amyc.utils.{Context, Pipeline}
import wasm._
import Instructions._
import Utils._

// Generates WebAssembly code for an Amy program
object CodeGen extends Pipeline[(Program, SymbolTable), Module] {
  def run(ctx: Context)(v: (Program, SymbolTable)): Module = {
    val (program, table) = v

    // Generate code for an Amy module
    def cgModule(moduleDef: ModuleDef): List[Function] = {
      val ModuleDef(name, defs, optExpr) = moduleDef
      // Generate code for all functions
      defs.collect { case fd: FunDef if !builtInFunctions(fullName(name, fd.name)) =>
        cgFunction(fd, name, false)
      } ++
      // Generate code for the "main" function, which contains the module expression
      optExpr.toList.map { expr =>
        val mainFd = FunDef(Identifier.fresh("main"), Nil, TypeTree(IntType), expr)
        cgFunction(mainFd, name, true)
      }
    }

    // Generate code for a function in module 'owner'
    def cgFunction(fd: FunDef, owner: Identifier, isMain: Boolean): Function = {
      // Note: We create the wasm function name from a combination of
      // module and function name, since we put everything in the same wasm module.
      val name = fullName(owner, fd.name)
      Function(name, fd.params.size, isMain){ lh =>
        val locals = fd.paramNames.zipWithIndex.toMap
        val body = cgExpr(fd.body)(locals, lh)
        val comment = Comment(fd.toString)
        if (isMain) {
          body <:> Drop // Main functions do not return a value,
                        // so we need to drop the value generated by their body
        } else {
          comment <:> body
        }
      }
    }


    // Generate code for an expression expr.
    // Additional arguments are a mapping from identifiers (parameters and variables) to
    // their index in the wasm local variables, and a LocalsHandler which will generate
    // fresh local slots as required.
    def cgExpr(expr: Expr)(implicit locals: Map[Identifier, Int], lh: LocalsHandler): Code = {
      expr match {
        case IntLiteral(i) =>
          // Push i to the stack.
          // The comments are optional but can help you debug.
          Comment(expr.toString) <:> Const(i)

        case BooleanLiteral(v) =>
          Comment(expr.toString) <:> Const(if v 1 else 0)

        case StringLiteral(string) =>
          // WARNING could have problems if string is empty. Not sure of correctness
          Comment(expr.toString) <:> string.map(c => Const(c.toInt)).reduce(_ <:> _)

        case UnitLiteral =>
          Comment(expr.toString)

        case Plus(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Add

        case Minus(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Sub

        case Times(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Mul

        case Div(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Div

        case Mod(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Rem

        case LessThan(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Lt_s

        case LessEquals(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Le_s

        case And(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> And

        case Or(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Or

        case Equal(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Eq

        case Concat(lhs:String, rhs:String) => (lhs ++ rhs).map(c => Const(c.toInt)).reduce(_ <:> _)

        case Match(scrut, cases) =>
          val scrutLocal = lh.getFreshLocal()

          // Checks if a value matches a pattern.
          // Assumes value is on top of stack (and CONSUMES it)
          // Returns the code to check the value, and a map of bindings.
          def matchAndBind(pat: Pattern): (Code, Map[Identifier, Int]) = pat match {
            case WildcardPattern() =>
              // Always matches; drop the scrutinee and push 1 (true).
              (Comment(pat.toString) <:> Drop <:> Const(1), Map.empty)

            case IdPattern(id) =>
              val idLocal = lh.getFreshLocal()
              (Comment(pat.toString) <:>
              // Assign val to id.
              SetLocal(idLocal) <:>
              // Return true (IdPattern always matches).
              Const(1),
              // Let the code generation of the expression which corresponds to this pattern
              // know that the bound id is at local idLocal.
              Map(id -> idLocal))

            case LiteralPattern(lit) =>
              // Scrutinee is on stack; push the literal value and compare with Eq.
              val checkCode: Code = lit match {
                case IntLiteral(i)     => Const(i) <:> Eq
                case BooleanLiteral(b) => Const(if (b) 1 else 0) <:> Eq
                case UnitLiteral()     => Drop <:> Const(1)
              }
              (Comment(pat.toString) <:> checkCode, Map.empty)

            case CaseClassPattern(constr, args) =>
              val constrSig = table.getConstructor(constr).get
              val adtLocal  = lh.getFreshLocal()

              // Store the ADT pointer and check its constructor tag.
              val storePtr: Code = SetLocal(adtLocal)
              val checkTag: Code = GetLocal(adtLocal) <:> Load <:> Const(constrSig.index) <:> Eq

              // For each field, load it, recursively check the sub-pattern, AND with running result.
              val (fullCheck, allBindings) =
                args.zipWithIndex.foldLeft((checkTag, Map.empty[Identifier, Int])) {
                  case ((accCode, accBindings), (arg, i)) =>
                    val loadField: Code = GetLocal(adtLocal) <:> adtField(i) <:> Load
                    val (argCheck, argBindings) = matchAndBind(arg)
                    (accCode <:> loadField <:> argCheck <:> And, accBindings ++ argBindings)
                }

              (Comment(pat.toString) <:> storePtr <:> fullCheck, allBindings)
          }

          // Evaluate the scrutinee once and store it so we can reuse it for each case.
          val evalScrut: Code = cgExpr(scrut) <:> SetLocal(scrutLocal)

          // Build a nested if-else chain from last case to first.
          // Base is Unreachable: traps if no case matched (Amy MatchError).
          val casesCode: Code = cases.foldRight(Unreachable: Code) {
            case (MatchCase(pat, body), elseCode) =>
              val (checkCode, bindings) = matchAndBind(pat)
              val bodyCode = cgExpr(body)(locals ++ bindings, lh)
              GetLocal(scrutLocal) <:> checkCode <:>
              If_i32 <:>
                bodyCode <:>
              Else <:>
                elseCode <:>
              End
          }

          Comment(expr.toString) <:> evalScrut <:> casesCode

        case _ => ???
      }
    }

    Module(
      program.modules.last.name.name,
      defaultImports,
      globalsNo,
      wasmFunctions ++ (program.modules flatMap cgModule)
    )
  }
}
