package amyc
package codegen

import analyzer._
import amyc.ast.Identifier
import amyc.ast.SymbolicTreeModule.{Call => AmyCall, Div => AmyDiv, And => AmyAnd, Or => AmyOr, _}
import amyc.utils.{Context, Pipeline}
import wasm._
import Instructions._
import Utils._

// Generates WebAssembly code for an Amy program
object CodeGen extends Pipeline[(Program, SymbolTable), Module] {
  def run(ctx: Context)(v: (Program, SymbolTable)): Module = {
    val (program, table) = v

    // Generate code for an Amy module
    def cgModule(moduleDef: ModuleDef): List[Function] = {
      val ModuleDef(name, defs, optExpr) = moduleDef
      // Generate code for all functions
      defs.collect { case fd: FunDef if !builtInFunctions(fullName(name, fd.name)) =>
        cgFunction(fd, name, false)
      } ++
      // Generate code for the "main" function, which contains the module expression
      optExpr.toList.map { expr =>
        val mainFd = FunDef(Identifier.fresh("main"), Nil, TypeTree(IntType), expr)
        cgFunction(mainFd, name, true)
      }
    }

    // Generate code for a function in module 'owner'
    def cgFunction(fd: FunDef, owner: Identifier, isMain: Boolean): Function = {
      // Note: We create the wasm function name from a combination of
      // module and function name, since we put everything in the same wasm module.
      val name = fullName(owner, fd.name)
      Function(name, fd.params.size, isMain){ lh =>
        val locals = fd.paramNames.zipWithIndex.toMap
        val body = cgExpr(fd.body)(locals, lh)
        val comment = Comment(fd.toString)
        if (isMain) {
          body <:> Drop // Main functions do not return a value,
                        // so we need to drop the value generated by their body
        } else {
          comment <:> body
        }
      }
    }


    // Generate code for an expression expr.
    // Additional arguments are a mapping from identifiers (parameters and variables) to
    // their index in the wasm local variables, and a LocalsHandler which will generate
    // fresh local slots as required.
    def cgExpr(expr: Expr)(implicit locals: Map[Identifier, Int], lh: LocalsHandler): Code = {
      expr match {
        case IntLiteral(i) =>
          // Push i to the stack.
          // The comments are optional but can help you debug.
          Comment(expr.toString) <:> Const(i)

        case BooleanLiteral(v) =>
          Comment(expr.toString) <:> Const(v ? 1: 0)

        case StringLiteral(string) =>
          // WARNING could have problems if string is empty. Not sure of correctness
          Comment(expr.toString) <:> string.map(c => Const(c.toInt)).reduce(_ <:> _)

        case UnitLiteral =>
          Comment(expr.toString)

        case Plus(lhs, rhs) => cgExpr(lhs) <:> Add <:> cgExpr(rhs)

        case Minus(lhs, rhs) => cgExpr(lhs) <:> Sub <:> cgExpr(rhs)

        case Times(lhs, rhs) => cgExpr(lhs) <:> Mul <:> cgExpr(rhs)

        case Div(lhs, rhs) => cgExpr(lhs) <:> Div <:> cgExpr(rhs)

        case Mod(lhs, rhs) => cgExpr(lhs) <:> Rem <:> cgExpr(rhs)

        case LessThan(lhs, rhs) => cgExpr(lhs) <:> Lt_s <:> cgExpr(rhs)

        case LessEquals(lhs, rhs) => cgExpr(lhs) <:> Le_s <:> cgExpr(rhs)

        case And(lhs, rhs) => cgExpr(lhs) <:> And <:> cgExpr(rhs)

        case Or(lhs, rhs) => cgExpr(lhs) <:> Or <:> cgExpr(rhs)

        case Equal(lhs, rhs) => cgExpr(lhs) <:> Eq <:> cgExpr(rhs)

        case Concat(lhs, rhs) => cgExpr(lhs) <:> Drop <:> cgExpr(rhs)   // WARNING this might be incorrect

        case Match(scrut, cases) =>

          // Checks if a value matches a pattern.
          // Assumes value is on top of stack (and CONSUMES it)
          // Returns the code to check the value, and a map of bindings.
          def matchAndBind(pat: Pattern): (Code, Map[Identifier, Int]) = pat match {
            case IdPattern(id) =>
              val idLocal = lh.getFreshLocal()
              (Comment(pat.toString) <:> 
              // Assign val to id.
              SetLocal(idLocal) <:> 
              // Return true (IdPattern always matches).
              Const(1),
              // Let the code generation of the expression which corresponds to this pattern
              // know that the bound id is at local idLocal.
              Map(id -> idLocal))
            
            case _ => ???
          }

          ???

        // Still have to do control flow
        
        case Variable(name) =>
          Comment(expr.toString) <:>
          GetLocal(locals(name))

        case Let(df, value, body) =>
          val localIdx = lh.getFreshLocal()
          Comment(expr.toString) <:>
          cgExpr(value) <:>
          SetLocal(localIdx) <:>
          cgExpr(body)(locals + (df.name -> localIdx), lh)

        case AmyCall(qname, args) =>
          val sig = table.getFunction(qname)
          if (sig.isDefined) {
            // Function call
            args.map(cgExpr) <:>
            Call(fullName(sig.get.owner, qname))
          } else {
            // Constructor call
            val constr = table.getConstructor(qname).get
            val oldMem = lh.getFreshLocal()
            val argAssignments = args.zipWithIndex.map { case (arg, i) =>
              GetLocal(oldMem) <:>
              Const((i + 1) * 4) <:>
              Add <:>
              cgExpr(arg) <:>
              Store
            }
            Comment(expr.toString) <:>
            GetGlobal(memoryBoundary) <:>
            SetLocal(oldMem) <:>
            GetGlobal(memoryBoundary) <:>
            Const((args.size + 1) * 4) <:>
            Add <:>
            SetGlobal(memoryBoundary) <:>
            GetLocal(oldMem) <:>
            Const(constr.index) <:>
            Store <:>
            argAssignments <:>
            GetLocal(oldMem)
          }

        case Error(msg) =>
          Comment(expr.toString) <:>
          cgExpr(msg) <:>
          Call("Std_printString") <:>
          Unreachable
          
        case _ => ???
      }
    }

    Module(
      program.modules.last.name.name,
      defaultImports,
      globalsNo,
      wasmFunctions ++ (program.modules flatMap cgModule)
    )
  }
}
